@section('title')
    Login
@endsection
<x-guest-layout>
    <x-auth-card>
        <x-slot name="logo">
            <a href="/">
                <x-application-logo class="h-20 fill-current text-gray-500 dark:text-gray-200" />
            </a>
        </x-slot>

        <!-- Session Status -->
        <x-session-status class="mb-4" />

        <!-- Validation Errors -->
        <x-validation-errors class="mb-4" :errors="$errors" />

        <form method="POST" action="{{ route('two-factor-auth') }}">
            @csrf

            <div class="text-center">

                <p class="text-xl font-semibold  text-gray-700 dark:text-gray-100 mb-4">Enter the two-step verification
                    code</p>
                <p class=" text-gray-500 dark:text-gray-200 mb-4">
                    6-digit code is generated by an app
                    <b>Google Authenticator</b>
                </p>

                <img src="{{ @asset('images/google-auth-icon.webp') }}" alt="google-auth-icon"
                    class="h-20 mb-6 mx-auto" />
            </div>

            <x-input-field name="one_time_password" label="2FA Code" placeholder="6 digit 2FA security code"
                pattern="[0-9]{6}" required />

            <div class="flex items-center mt-4">
                <button type="submit" class="btn btn-primary uppercase w-full justify-center">
                    Confirm
                </button>
            </div>
        </form>
    </x-auth-card>
</x-guest-layout>
